/**
 * PDF export: pattern image + fabric shopping list.
 */

export async function exportPdf(patternCanvas, palette) {
  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'letter',
  });

  // Title
  pdf.setFontSize(20);
  pdf.setFont(undefined, 'bold');
  pdf.text('Appliqué Quilt Pattern', 15, 20);

  // Pattern image
  const patternDataUrl = patternCanvas.toDataURL('image/png');
  const imgWidth = 180;
  const imgHeight = (patternCanvas.height / patternCanvas.width) * imgWidth;
  pdf.addImage(patternDataUrl, 'PNG', 15, 30, imgWidth, imgHeight);

  let yPos = 30 + imgHeight + 15;

  // Fabric list header
  pdf.setFontSize(14);
  pdf.setFont(undefined, 'bold');
  pdf.text('Fabric Shopping List', 15, yPos);
  yPos += 10;

  pdf.setFontSize(10);
  pdf.setFont(undefined, 'normal');

  for (const color of palette) {
    // Color swatch box
    pdf.setFillColor(color.rgb[0], color.rgb[1], color.rgb[2]);
    pdf.rect(15, yPos - 4, 8, 8, 'F');

    // Fabric info
    const fabricInfo = color.fabric
      ? `${color.fabric.name} (${color.fabric.number})`
      : color.hex;

    pdf.text(`${fabricInfo}  —  ${color.percentage}%`, 28, yPos);

    // Show matched fabric swatch next to the quantized color if different
    if (color.fabric) {
      pdf.setFillColor(color.fabric.rgb.r, color.fabric.rgb.g, color.fabric.rgb.b);
      pdf.rect(15, yPos + 5, 8, 4, 'F');
      pdf.setFontSize(8);
      pdf.setTextColor(100);
      pdf.text(`Fabric match: ${color.fabric.hex}`, 28, yPos + 8);
      pdf.setFontSize(10);
      pdf.setTextColor(0);
      yPos += 10;
    }

    yPos += 12;

    if (yPos > 255) {
      pdf.addPage();
      yPos = 20;
    }
  }

  // Footer
  const pageCount = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text(`Generated by Appliqué Studio — Page ${i} of ${pageCount}`, 15, 270);
  }

  pdf.save('applique-pattern.pdf');
}
